### ISSUE TITLE
Cannot delete an index name malformed

### ISSUE THREAD

**Issue by allx0** [ElasticHQ/elasticsearch-HQ#152]
Because the variable %{idx} was not set in logstash an Index was nammed like this:

prod%{idx}-2014.05.07

ElasticsearchHQ display it in the list of Index but we can't Delete it or Get Information on it

**Comment by arcanericky** [comment]
This has caused me some problems too. The root cause is % must be escaped as %% when executing the REST calls to Elasticsearch. ElasticHQ fails to do this. You'll need to fall back on REST calls using cURL for these indices. For example, use ```curl -g -XDELETE http://localhost:9200/prod%%{idx}-2014.05.07/``` to delete the index (note the use of %% to escape the % character).
